public class InterfaceClass implements InterfaceClass1, InterfaceClass2
{
    public void Add()
    {
        integer a=11;
        integer b=7;
        integer c=a+b;
        System.debug(c);
    }
    public void Sub()
    {
        integer a=11;
        integer b=7;
        integer c=a-b;
        System.debug(c);
    }
    public void Mul()
    {
        
    }
    public void Div()
    {
        
    }
}